import Head from "next/head";
import TodoPage from "../components/TodoPage";
import { useEffect, useState } from "react";
import Landing from "../components/Landing";

export default function Home() {
  // permet de savoir quel composant monter selon que l'utilisateur est authentifié ou non
  const [auth, setAuth] = useState();

  useEffect(() => {
    // si aucun JWT
    if (!localStorage.getItem("accessToken")) {
      setAuth(false);
    }

    // si précence d'un JWT
    if (localStorage.getItem("accessToken")) {
      setAuth(true);
    }
  }, []);

  return (
    // si utilisateur non auth -> landing page; si utilisateur auth -> todos page
    <div>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!auth ? <Landing /> : <TodoPage />}
    </div>
  );
}
